# Generated by Django 6.0 on 2025-12-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('symptoms', models.TextField()),
                ('days_noticed', models.PositiveIntegerField()),
                ('medical_history', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('fitness_level', models.CharField(max_length=50)),
                ('hygiene_level', models.CharField(max_length=50)),
                ('sleep_hours', models.FloatField()),
                ('stress_level', models.CharField(max_length=50)),
                ('water_intake', models.CharField(max_length=50)),
                ('extra_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
