# Generated by Django 6.0 on 2025-12-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_checksymptom_ai_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checksymptom',
            old_name='extra_notes',
            new_name='extra_details',
        ),
    ]
